name: Release nightly

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
#  schedule:
#    - cron: "45 23 * * *"

jobs:
  prepare_release:
    runs-on: windows-2022
    outputs:
      release_ref: ${{ steps.gen_tag.outputs.release_ref }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "nanvr/NaNVR"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Generate tag, set release ref
        id: gen_tag
        env:
          RUST_BACKTRACE: 1
        run: |
          $out = cargo xtask bump --is-nightly
          echo $out
          echo "::set-output name=version_tag::$(echo $out | sls -CaseSensitive -Pattern '^v.*$')"
          echo "::set-output name=release_ref::$(git rev-parse HEAD)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Release tag is taken from the gen_tag job.
          tag_name: ${{ steps.gen_tag.outputs.version_tag }}
          release_name: NaNVR ${{ steps.gen_tag.outputs.version_tag }}
          # TODO: gather commit messages to post here in the body
          body: |
            Nightly release of NaNVR: ${{ steps.gen_tag.outputs.version_tag }}
            Generated from commit: nanvr/NaNVR@${{ steps.gen_tag.outputs.release_ref }}
          draft: true
          prerelease: false

  build_streamer:
    runs-on: ubuntu-22.04
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "nanvr/NaNVR"
          ref: ${{ needs.prepare_release.outputs.release_ref }}
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        env:
          RUST_BACKTRACE: 1
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 25088A0359807596
          echo "deb http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/pipewire-upstream.list
          sudo apt-get update
          sudo apt-get install libfuse2 build-essential pkg-config nasm libva-dev libdrm-dev libvulkan-dev libx264-dev libx265-dev cmake libasound2-dev libjack-jackd2-dev libxrandr-dev libunwind-dev libffmpeg-nvenc-dev nvidia-cuda-toolkit libgtk-3-dev libpipewire-0.3-dev libspa-0.2-dev
          cp nanvr/xtask/deb/cuda.pc /usr/share/pkgconfig

      - name: Build and package
        id: build
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo xtask bump --is-nightly
          cargo xtask package-streamer --enable-nvenc

      - name: Upload linux streamer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./build/nanvr_streamer_linux.tar.gz
          asset_name: nanvr_streamer_linux.tar.gz
          asset_content_type: application/gzip

  build_streamer_debug:
    runs-on: ubuntu-22.04
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "nanvr/NaNVR"
          ref: ${{ needs.prepare_release.outputs.release_ref }}
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        env:
          RUST_BACKTRACE: 1
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 25088A0359807596
          echo "deb http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/pipewire-upstream.list
          sudo apt-get update
          sudo apt-get install libfuse2 build-essential pkg-config nasm libva-dev libdrm-dev libvulkan-dev libx264-dev libx265-dev cmake libasound2-dev libjack-jackd2-dev libxrandr-dev libunwind-dev libffmpeg-nvenc-dev nvidia-cuda-toolkit libgtk-3-dev libpipewire-0.3-dev libspa-0.2-dev
          cp nanvr/xtask/deb/cuda.pc /usr/share/pkgconfig

      - name: Build and package
        id: build
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo xtask prepare-deps --platform linux
          cargo xtask bump --is-nightly
          cargo xtask build-streamer
          tar -czvf ./build/nanvr_streamer_linux.tar.gz -C ./build nanvr_streamer_linux

      - name: Upload streamer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./build/nanvr_streamer_linux.tar.gz
          asset_name: nanvr_streamer_linux_debug.tar.gz
          asset_content_type: application/gzip

  build_launcher:
    runs-on: ubuntu-22.04
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "nanvr/NaNVR"
          ref: ${{ needs.prepare_release.outputs.release_ref }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        env:
          RUST_BACKTRACE: 1
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev

      - name: Build and package
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo xtask bump --is-nightly
          cargo xtask package-launcher

      - name: Upload linux launcher
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./build/nanvr_launcher_linux.tar.gz
          asset_name: nanvr_launcher_linux.tar.gz
          asset_content_type: application/gzip

  build_flatpak_bundle:
    runs-on: ubuntu-latest
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "nanvr/NaNVR"
          ref: ${{ needs.prepare_release.outputs.release_ref }}

      - name: Build and install dependencies
        env:
          RUST_BACKTRACE: 1
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build and package flatpak (.flatpak)
        id: build_flatpak
        run: |
          sudo flatpak-builder --repo=.flatpak-repo --install-deps-from=flathub --force-clean --default-branch=stable --arch=x86_64 .flatpak-build-dir nanvr/xtask/flatpak/com.valvesoftware.Steam.Utility.nanvr.json
          flatpak build-bundle .flatpak-repo com.valvesoftware.Steam.Utility.nanvr.flatpak com.valvesoftware.Steam.Utility.nanvr stable --runtime
      - name: Upload flatpak streamer for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: com.valvesoftware.Steam.Utility.nanvr.flatpak
          asset_name: com.valvesoftware.Steam.Utility.nanvr.flatpak
          asset_content_type: application/octet-stream

  build_android_client:
    runs-on: ubuntu-latest
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "nanvr/NaNVR"
          ref: ${{ needs.prepare_release.outputs.release_ref }}
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: android-actions/setup-android@v3
        with:
          packages: "platforms;android-32"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Build and package
        env:
          RUST_BACKTRACE: 1
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cargo xtask bump --is-nightly
          cargo xtask package-client
          cargo xtask package-client-lib

      - name: Sign apk
        uses: ilharp/sign-android-release@v1
        id: sign_apk
        with:
          releaseDir: build/nanvr_client_android
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Upload apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_apk.outputs.signedFile }}
          asset_name: nanvr_client_android.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Upload client library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./build/nanvr_client_core.zip
          asset_name: nanvr_client_core.zip
          asset_content_type: application/zip

  publish_release:
    runs-on: ubuntu-latest
    needs:
      [
        prepare_release,
        build_streamer,
        build_streamer_debug,
        build_launcher,
        build_flatpak_bundle,
        build_android_client,
      ]
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
